### ISSUE TITLE
ctx.arc()

### ISSUE THREAD

**Issue by hemogk** [joshua-gould/canvas2pdf#10]
I think there is a bug with ctx.arc() when used with ctx.fill().
Here is an example:

```
ctx.beginPath();
ctx.moveTo(300,300); //0
ctx.lineTo(300,270); //1
ctx.lineTo(180,270); //2
ctx.arc(180,220,50,1/2*Math.PI,Math.PI,false);
ctx.lineTo(130,100); //4
ctx.lineTo(100,100); //5
ctx.lineTo(100,220); //6
ctx.arc(180,220,80,Math.PI,1/2*Math.PI,true);
ctx.lineTo(300,300); //0
ctx.fillStyle = 'red';
ctx.fill();
ctx.stroke();
```
Gives you this drawing:
![image](https://user-images.githubusercontent.com/43432832/57519360-03d23400-7356-11e9-8251-37322ba93744.png)

To fix it, I rewrote arc() as following:

```
function myArc(x0,y0,r,a0,a1,counterclockwise){
	var delta=0.1;
	if(a0>a1 && counterclockwise==false){a1+=2*Math.PI;}
	if(a1>a0 && counterclockwise==true){a0+=2*Math.PI;}
	if(counterclockwise==true){
		for (var a=a0; a>=a1; a-=delta) {
			ctx.lineTo(x0+r*Math.cos(a),y0+r*Math.sin(a));
		}
	}else{
		for (var a=a0; a<=a1; a+=delta) {
			ctx.lineTo(x0+r*Math.cos(a),y0+r*Math.sin(a));
		}		
	}
}
ctx.beginPath();
ctx.moveTo(300,300); //0
ctx.lineTo(300,270); //1
ctx.lineTo(180,270); //2
myArc(180,220,50,1/2*Math.PI,Math.PI,false);
ctx.arc(180,220,50,1/2*Math.PI,Math.PI,false);
ctx.lineTo(130,100); //4
ctx.lineTo(100,100); //5
ctx.lineTo(100,220); //6
myArc(180,220,80,Math.PI,1/2*Math.PI,true);
ctx.lineTo(300,300); //0
ctx.fillStyle = 'red';
ctx.fill();
ctx.stroke();

```

And it gives this drawing:
![image](https://user-images.githubusercontent.com/43432832/57521072-45fd7480-735a-11e9-83e5-a12c21fc7ecf.png)

Maybe the start-angle and end-angle are inverted for some cases in your code.

**Comment by dankrusi** [comment]
I have a similar issue, but I think it has to do with the path closing/continuation and not the actual arc maths. In canvas2pdf the arc method builds a path and then calls this.doc.path(cmd) - it looks like this is closing the path...
