### ISSUE TITLE
blobStream is not defined 

### ISSUE THREAD

**Issue by sagarvibrant** [joshua-gould/canvas2pdf#13]
I'm Using in Angular 8, When i call 
var ctx = new canvas2pdf.Context(blobStream());
its throw - blobStream is not defined

**Comment by joshua-gould** [comment]
blobStream is required (
https://github.com/joshua-gould/canvas2pdf#dependencies)

**Comment by sagarvibrant** [comment]
In  `new canvas2pdf.PdfContext (blobStream()` I passed Only one Parameter but there in `canvas2pdf.js` there were two parameters 
 canvas2pdf.PdfContext = function (stream, options) {
    if (stream == null) {
      throw new Error('Stream must be provided.');
    }
    var _this = this;
    var doc = new PDFDocument(options);
    this.stream = doc.pipe(stream);
    this.doc = doc;
  
I dont understand what data passed in options parameter  . 

my code - 
 var pdfCanvas: any = document.querySelector('canvas');
      var ctx = new canvas2pdf.PdfContext(window.blobStream());
      ctx.fillStyle = 'yellow';
      ctx.fillRect(100, 100, 100, 100);
      pdfCanvas.src = ctx.stream.toBlobURL('application/pdf');

Its throw error 
PDFDocument is not defined


Thank you.

**Comment by joshua-gould** [comment]
You also need http://pdfkit.org installed.

**Comment by sagarvibrant** [comment]
Thanks @joshua-gould its removes my error,
Generated Url --     blob:http://localhost:4200/fa0ef7a8-3c65-479b-b0a4-53e605a06083 
but PDF is not open .
![blobPDF](https://user-images.githubusercontent.com/36664189/67399594-1b327000-f5ca-11e9-9ba8-7b99c8b7785d.png)

 var pdfCanvas: any = document.querySelector('canvas');
      var blobStream = window.blobStream();
      var ctx = new canvas2pdf.PdfContext(window.blobStream(), pdfCanvas);
      console.log(ctx);
      var blob = ctx.stream.toBlobURL('application/pdf');
      console.log(blob);
      window.open(blob, 'example.pdf', true);

I use `fabric js canvas`.

**Comment by joshua-gould** [comment]
You have to issue drawing commands after creating an instance of canvas2pdf.PdfContext.

**Comment by sagarvibrant** [comment]
@joshua-gould  Can you please give me `plunker` or `stackblitz` demo.

**Comment by joshua-gould** [comment]
see https://github.com/joshua-gould/canvas2pdf#browser-usage

**Comment by sagarvibrant** [comment]
![canvas2pdf_fabricdata](https://user-images.githubusercontent.com/36664189/67465839-972cc680-f663-11e9-8244-4d5cda704aea.png)
This is canvas data what I get.
How can I use `canvas2pdf` with `fabric js` canvas ?
