### ISSUE TITLE
ctx.addPage()

### ISSUE THREAD

**Issue by hemogk** [joshua-gould/canvas2pdf#15]
I need to make a multi-page PDF but the function ctx.addPage() is missing.
Adding the following in the file canvas2pdf.js file solved it.
```
  /**
   * Add a new page
   */
  canvas2pdf.PdfContext.prototype.addPage = function () {
    this.doc.addPage();
  };
```

**Comment by joshua-gould** [comment]
Thanks. You can also get the PDFDocument instance using ctx.doc to call methods directly on PDFDocument without adding methods to canvas2pdf.

**Comment by hemogk** [comment]
I didn't know I could do that. 
Actually is simpler to just call ctx.doc.addPage();
Thank you
