### ISSUE TITLE
AMD dependency for PDFDocument

### ISSUE THREAD

**Issue by mateuszluczak** [joshua-gould/canvas2pdf#2]
Your library works great, but we've encountered a problem when used with AMD and require.js.

You are explicitly calling for global `PDFDocument`, which causes a problem as this dependency should be defined in `define` for AMD. `pdfkit` also supports AMD so it's not possible to shim it to global without ugly exposing `PDFDocument` to global.

Would be great if you could fix this, or let me know if you are open to PRs.

**Comment by joshua-gould** [comment]
Sorry for the delay in my response. It would be great if you submitted a PR that fixed this issue. Thanks.
