### ISSUE TITLE
**Abandoned**: Use node canvas instead

### ISSUE THREAD

**Issue by ShaMan123** [joshua-gould/canvas2pdf#22]
https://github.com/Automattic/node-canvas#pdf-output-support

good luck to all

**Comment by joshua-gould** [comment]
The library still works-see https://joshua-gould.github.io/canvas2pdf/demo.html

**Comment by ShaMan123** [comment]
Sorry
I saw open tickets from ages ago and no commit from 2021...
I pred to a firk with a few fixes if you are interested

**Comment by joshua-gould** [comment]
Sure, PRs are welcome. Thanks
