### ISSUE TITLE
font props support

### ISSUE THREAD

**Issue by ebigtm** [joshua-gould/canvas2pdf#36]
Hi and thank you for this amazing solution, just wanted to check if im missing something regarding font family and font size, for some reason no matter what i do, inside the pdf the text stays with the default font.

Any idea why?
<img width="1213" alt="image" src="https://github.com/joshua-gould/canvas2pdf/assets/78391102/6d97085e-c786-4c7e-86dd-8582e884cc45">

**Comment by joshua-gould** [comment]
Please see https://pdfkit.org/docs/text.html#fonts

**Comment by ebigtm** [comment]
thank you
