### ISSUE TITLE
fill()

### ISSUE THREAD

**Issue by hemogk** [joshua-gould/canvas2pdf#5]
Hi again,

I am still testing your library and found a problem with the fill() function.
The following is suppose to produce a red rectangle with black border:
```
ctx.beginPath();
ctx.moveTo(170, 80);
ctx.rect(20,20,150,100);
ctx.fillStyle = 'red';
ctx.fill();
ctx.strokeStyle = 'black';
ctx.lineWidth = 5;
ctx.stroke();
```
Like this one:
![image](https://user-images.githubusercontent.com/43432832/45804215-7377ae00-bcf6-11e8-8c9c-4db4636e58ce.png)
But instead I just get a red rectangle without border:
![image](https://user-images.githubusercontent.com/43432832/45804043-0f54ea00-bcf6-11e8-927b-1ba980bbb03a.png)

**Comment by joshua-gould** [comment]
This is a known issue-Calling fill and then stroke consecutively only executes fill
