### ISSUE TITLE
How to use inside node?

### ISSUE THREAD

**Issue by sinanerdem** [joshua-gould/canvas2pdf#6]
I would like to use canvas2pdf inside node.js. My main idea is to put the js inside AWS Lambda and whenever a request comes, I would like to create a pdf and put to S3. But I cannot find how to do it without blobStream. Is there any example regarding this? Thank you.

**Comment by joshua-gould** [comment]
PDFDocument = require('pdfkit')

const fs = require('fs')
const canvas2pdf = require('canvas2pdf')
const file = fs.createWriteStream('example.pdf')
var ctx = new canvas2pdf.PdfContext(file)

//draw your canvas like you would normally
ctx.fillStyle = 'yellow'
ctx.fillRect(100, 100, 100, 100)
// more canvas drawing, etc...

//convert your PDF to a Blob and save to file
ctx.stream.on('finish', function () {
  file.end()
})
ctx.end()

**Comment by sinanerdem** [comment]
oh very nice. tried it and works. thank you.

just one thing, i needed to:
const canvas2pdf = require('./src/canvas2pdf')
