### ISSUE TITLE
Do we need jsdom or node-canvas?

### ISSUE THREAD

**Issue by sinanerdem** [joshua-gould/canvas2pdf#7]
From canvas2svg page:

> You can use canvas2svg with node.js using jsdom with node-canvas. To do this first create a new document object, and then create a new instance of C2S based on that document:
> 
> var canvas = require('canvas'),
>     jsdom = require('jsdom'),
>     C2S = require('canvas2svg');
> 
> var document = jsdom.jsdom();
> var ctx = new C2S({document: document});
> 
> // ... drawing code goes here ...

Do we need to do the same in order to use canvas2pdf in node.js? Whats the benefit of jsdom?

**Comment by joshua-gould** [comment]
canvas2svg requires the DOM, but canvas2pdf does not use the DOM.
