### ISSUE TITLE
Can we use existing canvas created by another library?

### ISSUE THREAD

**Issue by sinanerdem** [joshua-gould/canvas2pdf#8]
For example, fabric.js can create a canvas. Can I use this canvas or somehow convert to mock canvas used by canvas2pdf in order to create a pdf from it?

**Comment by wmerussi** [comment]
I'd like to know that also.

**Comment by sagarvibrant** [comment]
Any update ?

**Comment by nistaneznam** [comment]
I like to know that also. Can i load JSON exported in fabric into canvas2pdf canvas (mock)?

**Comment by 6Hat** [comment]
Since this was asked more than a year ago and no reply has been made, I can only assume that it is not possible. Has anyone found a good alternative? I am using fabric.js as well.

**Comment by ramonakira** [comment]
I was looking for this, but found that it is possible to save a canvas as a png or jpg using `toDataURL` (see https://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf). Then you'd use PDFKit to display the canvas as an image using the image loading described here: https://pdfkit.org/docs/images.html
